#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic
#+ except for TCP ports 22, 443 and 80.
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
ufw disable
apt install ufw
ufw default deny incoming
ufw allow 22
ufw allow 443
ufw allow 80
ufw enable