#!/usr/bin/env bash

key_name="school"
key_bits=4096
passphrase="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b "$key_bits" -N "$passphrase" -f "$key_name"

echo "RSA key pair generated successfully."
